### ISSUE TITLE
Fix deprecation warning "Param 'purge_networks' is deprecated."

### ISSUE THREAD

**Issue by Mattias-hogent** [HoGentTIN/infra-labs#27]
The CI/CD throws this deprecation warning at setup:
> "[DEPRECATION WARNING]: Param 'purge_networks' is deprecated. See the module
> docs for more information. This feature will be removed from community.docker
> in version 4.0.0. Deprecation warnings can be disabled by setting
> deprecation_warnings=False in ansible.cfg."

dockerlab/ansible/roles/dockerlab/tasks/main.yml
start line 85
```yaml
- name: Create a Docker container for Portainer
  docker_container:
    name: portainer
    image: portainer/portainer-ce
    state: started
    restart_policy: always
    ports:
      - 8000:8000
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - name: mgmt_net
    purge_networks: true
    networks_cli_compatible: true
    network_mode: default
  tags: dockerlab
```
to

```yaml
- name: Create a Docker container for Portainer
  docker_container:
    name: portainer
    image: portainer/portainer-ce
    state: started
    restart_policy: always
    ports:
      - 8000:8000
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    comparisons:
       networks: strict
    networks:
      - name: mgmt_net
    networks_cli_compatible: true
    network_mode: default
  tags: dockerlab
```
