### ISSUE TITLE
Voorgestelde inventory-file werkt niet op Windows hostsysteem - SSH key bad permissions

### ISSUE THREAD

**Issue by bertvv** [HoGentTIN/infra-labs#28]
De voorgestelde inventory-file gebruikt de door Vagrant gegenereerde SSH-sleutels om in te loggen op de VMs. Deze zijn immers zichtbaar binnen de VM via de `/vagrant`-directory. Als het hostsysteem echter Windows is, worden alle permissies van bestanden onder `/vagrant` getoond als 0777, wat niet aanvaardbaar is voor een private SSH-sleutel (moet 0600 zijn).

Alternatief is het wachtwoord `vagrant` te gebruiken:

```yaml
# inventory.yml
---
servers:
  vars:
    ansible_user: vagrant
    ansible_ssh_password: vagrant
    ansible_become: true
  hosts:
    srv100:
      ansible_host: 172.16.128.100
```

Dit is ook een aanleiding om een extraatje in de opgave te steken: er voor zorgen dat Ansible tóch met SSH-sleutels kan werken:

- Door de Vagrant-sleutels naar de `$HOME` van gebruiker vagrant te kopiëren (in `control.sh`)
- Door een nieuwe admin-gebruiker te creëren die op alle VMs kan inloggen en sudo-rechten heeft (nadee: catch-22 situatie)
